/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as SmtpRouteImport } from './routes/smtp'
import { Route as RemindersIdRouteImport } from './routes/reminders/$id'
import { Route as RemindersNewRouteImport } from './routes/reminders/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SmtpRoute = SmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIdRoute = RemindersIdRouteImport.update({
  id: '/reminders/$id',
  path: '/reminders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersNewRoute = RemindersNewRouteImport.update({
  id: '/reminders/new',
  path: '/reminders/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/smtp': typeof SmtpRoute
  '/reminders/$id': typeof RemindersIdRoute
  '/reminders/new': typeof RemindersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/smtp': typeof SmtpRoute
  '/reminders/$id': typeof RemindersIdRoute
  '/reminders/new': typeof RemindersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/smtp': typeof SmtpRoute
  '/reminders/$id': typeof RemindersIdRoute
  '/reminders/new': typeof RemindersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logs' | '/smtp' | '/reminders/$id' | '/reminders/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logs' | '/smtp' | '/reminders/$id' | '/reminders/new'
  id: '__root__' | '/' | '/logs' | '/smtp' | '/reminders/$id' | '/reminders/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  SmtpRoute: typeof SmtpRoute
  RemindersIdRoute: typeof RemindersIdRoute
  RemindersNewRoute: typeof RemindersNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smtp': {
      id: '/smtp'
      path: '/smtp'
      fullPath: '/smtp'
      preLoaderRoute: typeof SmtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/$id': {
      id: '/reminders/$id'
      path: '/reminders/$id'
      fullPath: '/reminders/$id'
      preLoaderRoute: typeof RemindersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/new': {
      id: '/reminders/new'
      path: '/reminders/new'
      fullPath: '/reminders/new'
      preLoaderRoute: typeof RemindersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  SmtpRoute: SmtpRoute,
  RemindersIdRoute: RemindersIdRoute,
  RemindersNewRoute: RemindersNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
